version: '3.3'

services:
  dev:
    build:
      context: ./sshd-smbd
      dockerfile: Dockerfile.gui
      args:
        USER: ${USER}
        UID: ${UID}
        PASSWD: ${PASSWD}
        HOSTIP: ${HOSTIP}
    restart: always
    volumes:
      - user-home:/home/${USER}
      - files:/srv/files
    networks:
      dev-net:
        ipv4_address: $MYMACHINE
    environment:
      - HOSTIP=$HOSTIP

  ftp:
    build:
      context: ./vsftpd-anon
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOSTIPADDR=$HOSTIP
    volumes:
      - files:/var/ftp:ro
    ports:
      - "$HOSTIP:20-21:20-21"
      - "$HOSTIP:65500-65515:65500-65515"

  tftp:
    build:
      context: ./tftpd-hpa
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files:/var/lib/tftpboot
    ports:
      - "$HOSTIP:69:69/udp"

  route-setup:
    build:
      context: ./route-setup
      dockerfile: Dockerfile
#    networks:
#      nonet: {}
    # restart: always
    privileged: true
    pid: "host"
    network_mode: "none"

volumes:
  user-home:
  files:

networks:
  dev-net:
    driver: bridge
    ipam:
      config:
      -
        subnet: $MYSUBNET_AND_MASK
#  nonet:
#    external:
#      name: none