version: '3.0'

services:
  builder:
    build:
      context: ./sshd-smbd
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
        PASSWD: ${PASSWD}
    restart: always
    volumes:
      - user-home:/home/${USER}


volumes:
  user-home:

